# Credenciales del proyecto
sonar.projectKey=LosTresMosquetones_diplo_gyc
sonar.organization=lostresmosquetones
sonar.projectName=diplo_gyc

# Carpetas donde está tu código fuente a analizar
sonar.sources=backend,frontend,bff

# Carpetas y archivos de prueba
sonar.tests=backend/src/test,frontend/src/test,bff/tests
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/test/**

# Carpetas y archivos a ignorar en el análisis de código fuente (pero no necesariamente en pruebas)
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.github/**,**/actions-runner/**,backend/src/test/**,frontend/src/test/**,bff/tests/**

# Codificación estándar
sonar.sourceEncoding=UTF-8

# Le decimos dónde están los compilados (.class)
sonar.java.binaries=backend/target/classes

# Le decimos a Sonar dónde leer el reporte de cobertura (JaCoCo)
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,bff/coverage/lcov.info
